[module]
    [module.hugoVersion]
        extended = true
        min = "0.120.0"
    [[module.imports]]
        path = "github.com/hugo-mods/icons"
    [[module.imports]]
        path = "github.com/hugo-mods/lazyimg"
    [[module.imports]]
        path = "github.com/hugo-mods/release-notify"